services:
  todo-app-frontend:
    image: todo-app-frontend-dev
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 5173:5173
    container_name: todo-app-frontend-dev # This will name the container todo-app-frontend-dev
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
      - CHOKIDAR_USEPOLLING=true
