services:
  ilari-flights-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ilari-flights-backend-prod-container

  ilari-flights-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ilari-flights-frontend-prod-container 
    environment:
      - VITE_API_BASE_URL=/api

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - ilari-flights-frontend
      - ilari-flights-backend
