services:
  backend:                              # The name of the service, can be anything
    image: exercise-12.5                # Declares which image to use
    build: ./todo-backend               # Declares where to build if image is not found
    ports:                              # Declares the ports to publish
      - 3000:3000