services:
  todo-frontend:
    build:
      context: ./todo-frontend # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./todo-frontend:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
      - /usr/src/app/node_modules
    ports:
      - 5173:5173
    container_name: todo-app-frontend-dev # This will name the container todo-app-frontend-dev
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
      - CHOKIDAR_USEPOLLING=true
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - todo-frontend # wait for the frontend container to be started